---
swagger: "2.0"
info:
  description: "API for RIHA info system approvals"
  version: "v1"
  title: "RIHA-Approver API"
  license:
    name: "MIT"
basePath: "/"
tags:
- name: "approval comments"
- name: "approvals"
schemes:
- "http"
paths:
  /systems/approvals:
    get:
      tags:
      - "approvals"
      summary: "List all approvals of all information systems"
      description: ""
      operationId: "listApprovals"
      parameters:
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      - name: "filter"
        in: "query"
        description: "filter options"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        description: "sorting options"
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: "field list"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PagedResponseApproval"
  /systems/{infoSystemUuid}/approvals:
    get:
      tags:
      - "approvals"
      summary: "List all information system approvals"
      description: ""
      operationId: "listInfoSystemApprovals"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      - name: "filter"
        in: "query"
        description: "filter options"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        description: "sorting options"
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: "field list"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PagedResponseApproval"
    post:
      tags:
      - "approvals"
      summary: "Create new information system approval"
      description: ""
      operationId: "createInfoSystemApproval"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Approval"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Approval"
  /systems/{infoSystemUuid}/approvals/{approvalId}:
    get:
      tags:
      - "approvals"
      summary: "Get single information system approval"
      description: ""
      operationId: "getInfoSystemApproval"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - name: "approvalId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Approval"
  /systems/{infoSystemUuid}/approvals/{approvalId}/comments:
    get:
      tags:
      - "approval comments"
      summary: "List all information system approval comments"
      description: ""
      operationId: "listInfoSystemApprovalComments"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - name: "approvalId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      - name: "filter"
        in: "query"
        description: "filter options"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        description: "sorting options"
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: "field list"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PagedResponseApprovalComment"
    post:
      tags:
      - "approval comments"
      summary: "Create new information system approval comment"
      description: ""
      operationId: "createInfoSystemApprovalComment"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - name: "approvalId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/ApprovalComment"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApprovalComment"
  /systems/{infoSystemUuid}/approvals/{approvalId}/comments/{commentId}:
    get:
      tags:
      - "approval comments"
      summary: "Get single information system approval comment"
      description: ""
      operationId: "getInfoSystemApprovalComment"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - name: "approvalId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "commentId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/ApprovalComment"
definitions:
  Approval:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      infoSystemUuid:
        type: "string"
        format: "uuid"
      dateCreated:
        type: "string"
        format: "date-time"
      title:
        type: "string"
      comment:
        type: "string"
      authorName:
        type: "string"
      authorPersonalCode:
        type: "string"
      organizationName:
        type: "string"
      organizationCode:
        type: "string"
      status:
        type: "string"
        enum:
        - "OPEN"
        - "CLOSED"
  ApprovalComment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      infoSystemUuid:
        type: "string"
        format: "uuid"
      dateCreated:
        type: "string"
        format: "date-time"
      approvalId:
        type: "integer"
        format: "int64"
      comment:
        type: "string"
      authorName:
        type: "string"
      authorPersonalCode:
        type: "string"
      organizationName:
        type: "string"
      organizationCode:
        type: "string"
  PagedResponse:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      content:
        type: "array"
        items:
          type: "object"
      size:
        type: "integer"
        format: "int32"
      page:
        type: "integer"
        format: "int32"
      totalPages:
        type: "integer"
        format: "int32"
  PagedResponseApproval:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      content:
        type: "array"
        items:
          $ref: "#/definitions/Approval"
      size:
        type: "integer"
        format: "int32"
      page:
        type: "integer"
        format: "int32"
      totalPages:
        type: "integer"
        format: "int32"
  PagedResponseApprovalComment:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      content:
        type: "array"
        items:
          $ref: "#/definitions/ApprovalComment"
      size:
        type: "integer"
        format: "int32"
      page:
        type: "integer"
        format: "int32"
      totalPages:
        type: "integer"
        format: "int32"
