---
swagger: "2.0"
info:
  description: "API for RIHA info system issues"
  version: "v1"
  title: "RIHA-Approver API"
  license:
    name: "MIT"
basePath: "/"
tags:
- name: "Issue events"
- name: "Issue timeline"
- name: "Issues"
schemes:
- "http"
paths:
  /issues:
    get:
      tags:
      - "Issues"
      summary: "List all issues of all information systems"
      description: ""
      operationId: "listIssues"
      parameters:
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      - name: "filter"
        in: "query"
        description: "filter options"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        description: "sorting options"
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: "field list"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PagedResponseIssue"
  /issues/{issueId}:
    get:
      tags:
      - "Issues"
      summary: "Get single information system issue"
      description: ""
      operationId: "getInfoSystemIssue"
      parameters:
      - name: "issueId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Issue"
    put:
      tags:
      - "Issues"
      summary: "Update issue"
      description: ""
      operationId: "updateStatus"
      parameters:
      - name: "issueId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Issue"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Issue"
  /issues/{issueId}/comments:
    get:
      tags:
      - "Issue events"
      summary: "List all issue comments"
      description: ""
      operationId: "listIssueComments"
      parameters:
      - name: "issueId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      - name: "filter"
        in: "query"
        description: "filter options"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        description: "sorting options"
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: "field list"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PagedResponseIssueComment"
    post:
      tags:
      - "Issue events"
      summary: "Create new issue comment"
      description: ""
      operationId: "createIssueComment"
      parameters:
      - name: "issueId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/IssueComment"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/IssueComment"
  /issues/{issueId}/comments/{commentId}:
    get:
      tags:
      - "Issue events"
      summary: "Get single issue comment"
      description: ""
      operationId: "getIssueComment"
      parameters:
      - name: "issueId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "commentId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/IssueComment"
  /issues/{issueId}/timeline:
    get:
      tags:
      - "Issue timeline"
      summary: "Get issue timeline"
      description: ""
      operationId: "getTimeline"
      parameters:
      - name: "issueId"
        in: "path"
        required: true
        type: "integer"
        format: "int64"
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PagedResponseEntity"
  /systems/{infoSystemUuid}/issues:
    get:
      tags:
      - "Issues"
      summary: "List all issues of information system"
      description: ""
      operationId: "listInfoSystemIssues"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - name: "page"
        in: "query"
        description: "page number"
        required: false
        type: "integer"
      - name: "size"
        in: "query"
        description: "page size"
        required: false
        type: "integer"
      - name: "filter"
        in: "query"
        description: "filter options"
        required: false
        type: "string"
      - name: "sort"
        in: "query"
        description: "sorting options"
        required: false
        type: "string"
      - name: "fields"
        in: "query"
        description: "field list"
        required: false
        type: "string"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/PagedResponseIssue"
    post:
      tags:
      - "Issues"
      summary: "Create new issue for information system"
      description: ""
      operationId: "createInfoSystemIssue"
      parameters:
      - name: "infoSystemUuid"
        in: "path"
        required: true
        type: "string"
        format: "uuid"
      - in: "body"
        name: "body"
        required: false
        schema:
          $ref: "#/definitions/Issue"
      responses:
        200:
          description: "successful operation"
          schema:
            $ref: "#/definitions/Issue"
definitions:
  Entity:
    type: "object"
    properties:
      entityType:
        type: "string"
        enum:
        - "ISSUE"
        - "ISSUE_COMMENT"
        - "ISSUE_EVENT"
  Issue:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      infoSystemUuid:
        type: "string"
        format: "uuid"
      dateCreated:
        type: "string"
        format: "date-time"
      title:
        type: "string"
      comment:
        type: "string"
      authorName:
        type: "string"
      authorPersonalCode:
        type: "string"
      organizationName:
        type: "string"
      organizationCode:
        type: "string"
      status:
        type: "string"
        enum:
        - "OPEN"
        - "CLOSED"
      entityType:
        type: "string"
        enum:
        - "ISSUE"
        - "ISSUE_COMMENT"
        - "ISSUE_EVENT"
  IssueComment:
    type: "object"
    properties:
      id:
        type: "integer"
        format: "int64"
      issueId:
        type: "integer"
        format: "int64"
      comment:
        type: "string"
      dateCreated:
        type: "string"
        format: "date-time"
      authorName:
        type: "string"
      authorPersonalCode:
        type: "string"
      organizationName:
        type: "string"
      organizationCode:
        type: "string"
      entityType:
        type: "string"
        enum:
        - "ISSUE"
        - "ISSUE_COMMENT"
        - "ISSUE_EVENT"
  PagedResponse:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      content:
        type: "array"
        items:
          type: "object"
      size:
        type: "integer"
        format: "int32"
      page:
        type: "integer"
        format: "int32"
      totalPages:
        type: "integer"
        format: "int32"
  PagedResponseEntity:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      content:
        type: "array"
        items:
          $ref: "#/definitions/Entity"
      size:
        type: "integer"
        format: "int32"
      page:
        type: "integer"
        format: "int32"
      totalPages:
        type: "integer"
        format: "int32"
  PagedResponseIssue:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      content:
        type: "array"
        items:
          $ref: "#/definitions/Issue"
      size:
        type: "integer"
        format: "int32"
      page:
        type: "integer"
        format: "int32"
      totalPages:
        type: "integer"
        format: "int32"
  PagedResponseIssueComment:
    type: "object"
    properties:
      totalElements:
        type: "integer"
        format: "int64"
      content:
        type: "array"
        items:
          $ref: "#/definitions/IssueComment"
      size:
        type: "integer"
        format: "int32"
      page:
        type: "integer"
        format: "int32"
      totalPages:
        type: "integer"
        format: "int32"
